### ISSUE TITLE
js-paloma-hook div being removed from the page causing Turbolinks 5 trouble

### ISSUE THREAD

**Issue by brendon** [kbparagua/paloma#101]
Hi there, I'm trying to figure out how to get Paloma working with Turbolinks 5 when the back and forward buttons are pressed.

It seems that (perhaps when Paloma `start()`s?) that the `js-paloma-hook` `<div>` gets removed from the page. This means that the cached copy of the page is not able to re-execute the Paloma controller code when the page is next displayed via forward or back.

Are you able to provide a bit of insight into this? In my particular situation, I'm initialising a `fullcalendar` calendar, that works when navigating using actual links to the calendar, but upon navigating away and back, the functionality of the calendar widget is broken presumably because all of the event handlers are destroyed etc...

**Comment by brendon** [comment]
Having investigated it a bit further, it is because the hook code removes itself once executed. I went back through the history of the code and that concept seems to have been introduced around the time that Turbolinks integration happened.

Can you give any insight into the rationale?

In Turbolinks 5, the `turbolinks:load` event is triggered on each page change including when navigating history. Script blocks on the restored page are always executed (both when loaded from the server and when loaded from the cache. This would hopefully mean we can just do away with removing the hook code.

In this case, what would be the side-effects that I haven't considered? Perhaps hook code brought in from AJAX requests? In that case maybe there can be two versions of hook code, one for the overall 'load' of a page from the server, the other for xhr requests?

**Comment by brendon** [comment]
Just an extra bit of thought:

Turbolinks 5 has the `turbolinks:before_cache` event that is fired just before the page is cached whilst navigating to a new page. This is their official place for teardown logic. I've had a go at it and it worked well for `fullcalendar` where I destroy the rendered calendar just before the page is cached, then when the page is restored, because I've commented out the node removal in `_hook.html.erb`, Paloma re-runs the initialisation code for that page and the calendar re-appears.

Perhaps the idea of teardown could be integrated into Paloma?

**Comment by aguynamedben** [comment]
I am also curious about the implications of this.

**Comment by brendon** [comment]
With the altered `_hook.html.erb` I had no problems with Paloma at all. It ran the code on every page restore/load as intended. My thoughts on Paloma specific teardown would be something like:

`turbolinks:before_cache` kicks off `Paloma.teardown()` which in turn calls a `teardown` method on the specific Paloma controller/action. It'd require restructuring the controller a bit perhaps, but it should be possible to do this in a backward compatible way?

**Comment by benphelps** [comment]
While this isn't a fix for Paloma, I decided to reimplement the parts I use myself.  Working fine with Rails 5 + Turbolinks,  perhaps it'll be useful to some of you.

https://gist.github.com/benphelps/dccde4d11370511f0d64be6563796fda

**Comment by mangust404** [comment]
Thank you for the solution, @brendon. It works fine for me.
For other people seeking for the answer how to implement it, you should find _hook.html.erb in your paloma gem, copy it into your `app/views/paloma/_hook.html.erb` and comment out (or delete) the line where paloma script removes itself.
For my paloma gem (5.1.0) I got:
```
<% id = "#{Time.now.to_i}#{(rand * 1000).ceil}" %>

<div class="js-paloma-hook" data-palomaid="<%= id %>">
  <script type="text/javascript">
    (function(){

      if ( !window['Paloma'] ) return true;
      Paloma.env = '<%= Rails.env %>';

      var id = "<%= id %>",
          request = <%= request.to_json.html_safe %>;

      Paloma.engine.setRequest({
        id: id,
        resource: request.resource,
        action: request.action,
        params: request.params
      });

      //var self  = document.querySelector("[data-palomaid='" + id + "']");
      //if (self) self.parentNode.removeChild(self);
    })();
  </script>
</div>
```

All you got to do next is to write an idempotent javascript code for your Paloma controllers. Under "idempotent" I mean that you should consider that your DOM/SVG/Canvas elements may contain data from previous executions.

**Comment by brendon** [comment]
It seems that this repo isn't the canonical one now. https://github.com/gnclmorais/paloma is.

@gnclmorais, could you enable the issues section on your repo so that we can transfer this through to there for investigation? I think it still needs some thought.

**Comment by gnclmorais** [comment]
Hey folks! I didn’t notice the issues were not active, but they are now! 📥

**Comment by brendon** [comment]
For those that are interested in this issue, you can follow it here: https://github.com/gnclmorais/paloma/issues/6
