### ISSUE TITLE
Paloma does not load Controller & action for ajax

### ISSUE THREAD

**Issue by datnt** [kbparagua/paloma#31]
I configure within routes.rb so that Controller Chat nested within Controller Page
- When I open web browser for the first time, access url: http://localhost:3000/pages/1
- This page with automatically make ajax call to: http://localhost:3000/pages/1/chat
- In the console log of firebug, I realize that Paloma did not load the mapping to Controller Chat, action Index
- But, when I refresh the page, console log showing that, it has loaded properly the Controller Chat, and action Index
- Since then, everything works properly.

This issue only occurs when open web browser, at firstly access to "http://localhost:3000/pages/1"

**Comment by kbparagua** [comment]
Considering solved as of version `5.0.0`
