### ISSUE TITLE
Paloma Controller doesn't work with ActionController::Live

### ISSUE THREAD

**Issue by toroidal-code** [kbparagua/paloma#47]
I'm trying to use both Paloma in order to set up an SSE request for one of my pages. However, Paloma doesn't seem to execute when  the `include ActionController::Live` directive is at the top of the Rails controller.

**Comment by Chili-Man** [comment]
I running into this issue with  paloma 4.1.1

**Comment by kbparagua** [comment]
Fixed since version `4.2.0`
