### ISSUE TITLE
Add support For Arbitrary Paloma Start

### ISSUE THREAD

**Issue by Undistraction** [kbparagua/paloma#56]
Currently Paloma is started from the hook, but this makes it difficult to incorporate into existing applications or applications where JS code needs to execute before Paloma runs.

Obviously `Paloma.engine.start();` can be called from anywhere, but it is hard-coded into the hook.

Please add a config options such as `auto` which, if set to false, doesn't start the engine in the hook, allowing it to be started when most appropriate in the application.

**Comment by fernandes** [comment]
@kbparagua on this issue https://github.com/kbparagua/paloma/issues/85 I reported, an `auto` option set as false would solve the problem! :smile:

**Comment by kbparagua** [comment]
@Undistraction Now implemented on version `5.0.0` via `Paloma.start()`
