### ISSUE TITLE
Automatically disable paloma when send_file or send_data is detected

### ISSUE THREAD

**Issue by brendon** [kbparagua/paloma#62]
I was having this error

```
undefined method `[]' for #<File:0x007ff8f3cf1e78>
```

When trying to use `send_file`. I found in one of your closed issues a mention of using `js false` to disable paloma, but I wondered if this couldn't be done automatically, or at least not raise an error in the first place but fail silently if the renderer doesn't comply?

**Comment by kbparagua** [comment]
Fixed since version `4.2.0`
