### ISSUE TITLE
Is there a way to add two, or more js for a controller or Action?

### ISSUE THREAD

**Issue by carloct** [kbparagua/paloma#72]
something like 

js 'Accounts#index' , 'Admin/Uploader#index'

**Comment by kbparagua** [comment]
@carloct I'm not sure what's your use case for this. But you can do something like this:

```js
var self = Paloma.controller('Accounts');

self.prototype.index = function(){
  // Do something here

  var UploaderController = Paloma.controller('Admin/Uploader');
  var uploader = new UploaderController(this.params);

  uploader.index();
}
```

But personally, I don't prefer this approach. I think it is better to just create a utility function to be called rather than executing 2 paloma actions.

**Comment by carloct** [comment]
Great, thanks
