### ISSUE TITLE
AJAX Rendering HTML & JS

### ISSUE THREAD

**Issue by mikeroher** [kbparagua/paloma#74]
My issue is that I'm trying to render HTML and JS at the same time (I think?). The HTML gets rendered as a response but the JS is never called (the Paloma hook is inserted). I followed the tutorial in the Wiki and it still won't work.
Here's my Categories Controller:
```ruby
  class CategoriesController < ApplicationController
      def show
        ## being passed to the html
        @category = Category.find(params[:id])
        @sections = @category.sections.as_json
        
        ## being passed to the js
        js id: params[:id]
        
        respond_to do |format|
          format.html { render :layout => false } if request.xhr?
        end
      end
    end
```

And here's the JS I'm using when Categories gets called:

```js
// found in /javascripts/palmoa/categories.js
  var CategoriesController = Paloma.controller('Categories');

  CategoriesController.prototype.show = function() {

    //drill_down_categories(this.params['id']);
    $(document).on('ready, page:change', drill_down_categories(this.params['id']));
  };
```

This calls the `drill_down_categories` method:

```js
//THIS NEVER GETS CALLED
drill_down_categories = function(AR_category_id) {
  //this is the link that makes the ajax request
  var category_name_clicked = $('.list-group-item[data-id=' + AR_category_id + ']');
  var categories_list = $('.categories-wrapper .list-group');
  category_name_clicked.on('ajax:success', function(data) {
    categories_list.html(data);
  });
};
```

Cheers!

**Comment by mikeroher** [comment]
I've decided to keep Paloma for non-Ajax. However, I'm just going to stick with regular Rails JS for Ajax. Thanks anyways!

**Comment by kbparagua** [comment]
@mikeroher 
I think the problem is not with Paloma.
This might be the problem:
```js
$(document).on('ready, page:change', drill_down_categories(this.params['id']));
```

According to jQuery documentation, the event string should be separated by **spaces**. In this case you 
are using **comma** to separate multiple events.

Try doing this instead:
```js
$(document).on('ready page:change', drill_down_categories(this.params['id']));
```

**Comment by mikeroher** [comment]
Thanks! I actually noticed that after I posted, and fixed it.

It didn't resolve the issue.
