### ISSUE TITLE
Should I still see my page-specific js file ?

### ISSUE THREAD

**Issue by misner** [kbparagua/paloma#76]
Hi,

Rails rookie here. found your superb gem through a blog post.

I implemented <insert paloma hook> on a deal_page.html
I want deals.js only to load on deals_page and NOt on the homepage.

Is it normal that on LOCAL mode (localhost:3000), when I check chromde dev tools list of files loaded I still see deals.js on the homepage?

**Comment by kbparagua** [comment]
@misner 

Paloma is not selectively LOADING javascript files, rather it is selectively EXECUTING javascript code.
So to answer your question, every js file will still be loaded, but not all of them will execute.

If your `deals.js` contains something like this:

```js
var DealsController = Paloma.controller('Deals');

DealsController.prototype.index = function(){
  // this will only execute on route deals#index
};
```
It will still be included/loaded on every page. But the `index` function will ONLY execute when you render the index page of Deals.

**Comment by misner** [comment]
thanks a lot for your reply.

I see.
I thought I could do with Paloma :
(A) only execute certain javascript depending on the loaded page
(B) also only load certain javascript according to the loaded page (why? to optimize the size of files loaded for that page. For example, why burden the load time with deals.js if I only need it when the page /deals.html load...

So if I get you right, I can only do the (A) with Paloma ? not B?

Rookie here :) so I'm trying to be sure I understand Paloma right.

**Comment by kbparagua** [comment]
@misner 
Yes. You can only do option B with Paloma.

I agree with you, you should minimize the javascript loaded on your home page to make sure that it will render fast. But for the rest of the page, I think it is alright to load all javascript. You may want to read about the Rails Asset Pipeline about it (http://guides.rubyonrails.org/asset_pipeline.html#main-features)
