### ISSUE TITLE
Support for JS on Ancestor Controllers?

### ISSUE THREAD

**Issue by fredngo** [kbparagua/paloma#77]
Suppose that we have controllers as such:

```ruby
class SearchesController < ActionController::Base
  def new
  end
end

class Search::BooksController < SearchesController
end

class Search::MagazinesController < SearchesController
end
```

I would like to run some common javascript for both book searches and magazine searches, so I write

```javascript
var SearchesController = Paloma.controller('Searches');

SearchesController.prototype.new = function(){
   alert('Hello Searcher!');
};
```

When I hit Search::BooksController#new, I expect the alert to pop up. However, it doesn't. Looking into the Paloma hook on that page, I see that `resource` is defined as `Search/Books`. 

```javascript
(function(){
  // ... Some Paloma stuff ...
  var request = {"resource":"Search/Books","action":"new","params":{}};
  // ... Some other Paloma stuff ...
})();
```

This implies that I'd have to write the following to get the javascript to run on both types of searches:

```javascript
var BooksController = Paloma.controller('Search/Books');
var MagazinesController = Paloma.controller('Search/Magazines');

BooksController.prototype.new = function(){
   alert('Hello Searcher!');
};
MagazinesController.prototype.new = function(){
   alert('Hello Searcher!');
};
```

...which is not ideal nor DRY.

It would be great if the paloma JS for ancestor controllers were to run also.

This is an admittedly contrived example, but I hope it illustrates what I'm getting at. In my particular use case I'm trying to encapsulate a base controller inside a gem.

Thank you for developing this gem!

**Comment by kbparagua** [comment]
@fredngo 

Currently, there are two ways to achieve what you are trying to do.

1.) Use a controller-wide Paloma setup.
https://github.com/kbparagua/paloma#controller-wide-setup

```ruby
class SearchesController < ActionController::Base
  def new
  end
end

class Search::BooksController < SearchesController
  # Use Searches Paloma controller instead of  Search/Books
  js 'Searches'
end

class Search::MagazinesController < SearchesController
  js 'Searches'
end
```


2.) OR you can create a new Paloma controller and inherit from an existing one.

```js
var SearchesController = Paloma.controller('Searches');

SearchesController.prototype.new = function(){
   alert('Hello Searcher!');
};

var BooksController = Paloma.controller('Search/Books');
$.extend(BooksController, Paloma.controller('Searches'));

var MagazinesController = Paloma.controller('Search/Magazines');
$.extend(MagazinesController, Paloma.controller('Searches'));
```

**Comment by fredngo** [comment]
Ah, thanks for providing alternatives. I'll give this a spin. Thanks for your time! I really didn't mean for this to turn into a support request instead of an issue. :)
