### ISSUE TITLE
Paloma init seems not to be called

### ISSUE THREAD

**Issue by OriaLogic** [kbparagua/paloma#78]
Hi there,

I think I settled everything up correctly but Paloma is still not working.

I required Paloma in application.js and Paloma is indeed accessible in my browser from window["Paloma"]. I can also see the div['js-paloma-hook"] in my HTML and I added a controller and the corresponding hook in my javascript.

When I run in my console:
```
Window.Paloma.executeHook();
Window.Paloma.engine.start();
```
my code is indeed executed... So I added in app/assets/javascripts/paloma/main with the code of the init.js file and now everything works correctly.

Do you know what I could be doing wrong?

Thanks in advance

**Comment by kbparagua** [comment]
@OriaLogic what version of Paloma are you using?

**Comment by OriaLogic** [comment]
Hi, version 4.2.0. I simply added the gem and bundled.

**Comment by kbparagua** [comment]
@OriaLogic Please read the installation instruction for `4.2.0`: https://github.com/kbparagua/paloma/tree/4.2.0#install
