### ISSUE TITLE
Executing twice (on first page load) with Turbolinks 5

### ISSUE THREAD

**Issue by fernandes** [kbparagua/paloma#85]
Hi @kbparagua !

My context:

* Using jquery-turbolinks for jquery scripts compatibility
* Using Turbolinks 5

Here's the deal, paloma execute `Paloma.engine.start();` on [document ready](https://github.com/kbparagua/paloma/blob/6be685b5e6a060db56b6713a8608dd4189f20a5a/vendor/assets/javascripts/paloma/init.js#L21-L31) (execution `#1`)

I added a hook for Turbolinks 5

```javascript
$(document).on('turbolinks:load', function(){
  Paloma.executeHook();
  Paloma.engine.start();
});
```

and on the first page load, its executed for the second time (`#2`), next turbolinks loads are ok, because they do not execute `paloma/init.js` engine start again.

my "solution" was (it's not cool because is access `_request`):

```javascript
$(document).on('turbolinks:load', function(){
  if ($('.js-paloma-hook').data('id') != parseInt(Paloma.engine._request.id)) {
    Paloma.executeHook();
    Paloma.engine.start();
  }
});
```

So on the first time `init.js` already set `_request` based on paloma hook, and the turbolinks just ignore, second time, as the request is set to the _old_ one, it executes the hook.

I don't know if it's a bug or what, just posting if I'm doing something wrong you can, please, point me on the right direct, or it stays here for a future reference.

**Comment by kbparagua** [comment]
@fernandes As on version `5.0.0`, Paloma will be started manually, and it will probably solve your issue here.
