### ISSUE TITLE
Is the app compatible with ie9 or ie10?When I use ie9/10, there is an error in my browser console.....

### ISSUE THREAD

**Issue by wanghewanghe** [kbparagua/paloma#98]
I use this gem in Rails 2.15 with Paloma 5.0. 

When I use ie9/10, there is an error in my browser console..

```
SCRIPT5007:Can't catch undefined or null referenced attribute ‘length’
```

**Comment by fab-girard** [comment]
It seems IE9/IE10 isn't able to get `before` attributes from BaseController prototype. A simple correction could be to change this line:
```this.entries = controller.before``` in before_callback_performer.js 
by:
```this.entries = controller.before || []```

I can pull the correction depending of opinion of @kbparagua

**Comment by msjonker** [comment]
Was this fixed? I'm receiving the error in IE9.

**Comment by fab-girard** [comment]
This fix works for me. You can find my fork here: 
https://github.com/Mapotempo/paloma
I'm waiting to know if @kbparagua is ok to merge it in this repo or not.

**Comment by wanghewanghe** [comment]
Thank you for your reply.Sorry for my late reply.I fixed this error by myself in August in fact.I think your method can resolve this problem also.Because I just add if in your code:`if (this.entries) {
      for (var i = 0, n = this.entries.length; i < n; i++) {
        var entry = this.entries[i];

        this._callbackList =
            this._callbackList.concat(this._getCallbacksIfForAction(entry));
      }
    }`
